
name: weather_presentation_app
description: Weather Presentation App (GetX + Open-Meteo) v3
publish_to: "none"
version: 1.0.2+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.1.2
  geolocator: ^9.0.2
  permission_handler: ^10.4.0
  shared_preferences: ^2.1.1
  weather_icons: ^3.0.0
  intl: ^0.18.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png
    - assets/icons/sun.svg
    - assets/icons/moon.svg
    - assets/icons/cloud.svg
    - assets/icons/rain.svg
    - assets/icons/snow.svg
    - assets/icons/storm.svg
